# Generated by Django 6.0.7 on 2026-09-05 12:50

from django.db import migrations, models


def seed_gallery_images(apps, schema_editor):
    Listing = apps.get_model('dashboard', 'Listing')
    Listing.objects.filter(slug='engineering-mechanics-textbook').update(
        image_urls=[
            'https://placehold.co/640x480?text=Engineering+Mechanics+Textbook',
            'https://placehold.co/640x480?text=Textbook+Inside',
        ],
    )
    Listing.objects.filter(slug='scientific-calculator').update(
        image_urls=[
            'https://placehold.co/640x480?text=Scientific+Calculator',
            'https://placehold.co/640x480?text=Calculator+Case',
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seed_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_gallery_images, migrations.RunPython.noop),
    ]
