# Generated by Django 6.0.7 on 2026-10-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_listingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.listingreview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
