# Generated by Django 6.0.7 on 2026-08-11 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('campus_code', models.CharField(
                    max_length=2,
                    unique=True
                )),
                ('campus_name', models.CharField(
                    max_length=150,
                    unique=True
                )),
            ],
        ),

        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('college_name', models.CharField(
                    max_length=150,
                    unique=True
                )),
                ('campus', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='colleges',
                    to='accounts.campus'
                )),
            ],
        ),

        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('password', models.CharField(
                    max_length=128,
                    verbose_name='password'
                )),
                ('last_login', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='last login'
                )),
                ('is_superuser', models.BooleanField(
                    default=False,
                    help_text='Designates that this user has all permissions without explicitly assigning them.',
                    verbose_name='superuser status'
                )),
                ('email', models.EmailField(
                    max_length=254,
                    unique=True
                )),
                ('email_verified', models.BooleanField(
                    default=False
                )),
                ('is_first_login', models.BooleanField(
                    default=True
                )),
                ('first_name', models.CharField(
                    max_length=100
                )),
                ('middle_name', models.CharField(
                    blank=True,
                    max_length=100
                )),
                ('last_name', models.CharField(
                    max_length=100
                )),
                ('contact_num', models.CharField(
                    max_length=11,
                    unique=True
                )),
                ('role', models.CharField(
                    choices=[
                        ('USER', 'User'),
                        ('ADMIN', 'Admin')
                    ],
                    default='USER',
                    max_length=10
                )),
                ('is_active', models.BooleanField(
                    default=True
                )),
                ('is_staff', models.BooleanField(
                    default=False
                )),
                ('profile_picture', models.ImageField(
                    blank=True,
                    null=True,
                    upload_to='uploads/'
                )),
                ('date_joined', models.DateTimeField(
                    auto_now_add=True
                )),
                ('groups', models.ManyToManyField(
                    blank=True,
                    help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.group',
                    verbose_name='groups'
                )),
                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    help_text='Specific permissions for this user.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.permission',
                    verbose_name='user permissions'
                )),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('program_name', models.CharField(
                    max_length=150
                )),
                ('college', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='programs',
                    to='accounts.college'
                )),
            ],
        ),

        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('major_name', models.CharField(
                    max_length=150
                )),
                ('program', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='majors',
                    to='accounts.program'
                )),
            ],
        ),

        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('staff_id', models.CharField(
                    max_length=7,
                    unique=True
                )),
                ('staff_type', models.CharField(
                    choices=[
                        ('TEACHING', 'Teaching Staff'),
                        ('NON_TEACHING', 'Non-Teaching Staff')
                    ],
                    max_length=20
                )),
                ('campus', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='staff',
                    to='accounts.campus'
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='staff_profile',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),

        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('student_id', models.CharField(
                    max_length=10,
                    unique=True
                )),
                ('year_level', models.CharField(
                    blank=True,
                    choices=[
                        ('1', '1st Year'),
                        ('2', '2nd Year'),
                        ('3', '3rd Year'),
                        ('4', '4th Year'),
                        ('5', '5th Year'),
                        ('6', '6th Year')
                    ],
                    max_length=1,
                    null=True
                )),
                ('major', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='students',
                    to='accounts.major'
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='student_profile',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),

        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(
                fields=('college', 'program_name'),
                name='unique_program_per_college'
            ),
        ),

        migrations.AddConstraint(
            model_name='major',
            constraint=models.UniqueConstraint(
                fields=('program', 'major_name'),
                name='unique_major_per_program'
            ),
        ),
    ]