# Generated by Django 6.0.7 on 2026-10-04 12:11

import apps.messaging.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Waiting for buyer'), ('submitted', 'Waiting for seller'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='requested', max_length=10)),
                ('is_service', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('gcash', 'GCash'), ('cash', 'Cash on hand')], max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=30)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to=apps.messaging.models.purchase_proof_upload_to)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('buyer_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='messaging.conversation')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='messaging.message')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_start'], name='messaging_p_status_e5771a_idx'), models.Index(fields=['conversation', 'status'], name='messaging_p_convers_d5c7dd_idx')],
            },
        ),
    ]
