# Generated by Django 6.0.7 on 2026-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('purchase_request', 'Purchase request')], default='text', max_length=20),
        ),
    ]
